
apiVersion: v1
kind: Service
metadata:
  name: localdb-nodeport
  namespace: postgres
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: localdb
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007